package nl.remcoder.adventofcode;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

class Day7Test {
    private Day7 testSubject;

    @BeforeEach
    void setUp() {
        testSubject = new Day7();
    }

    @Test
    void part1Case1() {
        String data = """
                      .......S.......
                      ...............
                      .......^.......
                      ...............
                      ......^.^......
                      ...............
                      .....^.^.^.....
                      ...............
                      ....^.^...^....
                      ...............
                      ...^.^...^.^...
                      ...............
                      ..^...^.....^..
                      ...............
                      .^.^.^.^.^...^.
                      ...............
                      """;

        assertEquals(21, testSubject.handlePart1(data.lines()));
    }

    @Test
    void testPart1Input() throws Exception {
        assertEquals(1658, testSubject.handlePart1(
                Files.lines(Paths.get("../aoc-inputs/2025/day7/input"))));
    }

    @Test
    void part2Case1() {
        String data = """
                      .......S.......
                      ...............
                      .......^.......
                      ...............
                      ......^.^......
                      ...............
                      .....^.^.^.....
                      ...............
                      ....^.^...^....
                      ...............
                      ...^.^...^.^...
                      ...............
                      ..^...^.....^..
                      ...............
                      .^.^.^.^.^...^.
                      ...............
                      """;

        assertEquals(40, testSubject.handlePart2(data.lines()));
    }

    @Test
    void testPart2Input() throws Exception {
        assertEquals(53916299384254L, testSubject.handlePart2(
                Files.lines(Paths.get("../aoc-inputs/2025/day7/input"))));
    }
}